# -*- coding: utf-8 -*-
"""LabSection04_21101255_CSE221LabAssignment03_Summer2022.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pCLbCd4eNt-y9iWvMymsowrX9oS89jg0
"""

# -*- coding: utf-8 -*-
"""
Created on Sat Oct 22 19:18:13 2022

@author: Rubayat Khan
"""
# CSE221 Lab 03 Graphs

def readFile():
    # reading file from as input
    # change the file name according to yours
    f = open("graph.txt", "r")
    
    # first line of input contains the number of vertices in the graph
    n = f.readline()
    # strip() gets rid of the new line
    # try printing n without strip()
    # print(n.strip())
    n = n.strip()
    # print(type(n))
    # n is of type string. we need to convert it to int
    n=int(n)
    # print(type(n))
    
    # the second line of the file contains the number of connections
    c = f.readline()
    c = c.strip()
    c = int(c)
    # print(c)
    
    buildGraphUsingDictionary(c,f)
    
    buildGraphUsingListofLists(c,f)  
#v esryfg sfvxfvsdhgfvhfhjsvdfvgsdjvh vdfvj


# we want to build an adjacency list like the following
# A -> b,C 
# One vertex can be connected to multiple vertices
# which means multiple values are associated with one vertex
# one data structure that can be used is a dictionary of lists
# {A:[B,C]}

def buildGraphUsingDictionary(c,f): 
    # creating a dictionary
    graph = {}
    # the following lines of the file contain the connections
    # creating a directed graph (a,b means a is connected to b)
    
    counter = 0
    while (counter<c):
        line = f.readline() # reading each libe
        a,b = line.split(",") # splitting the vertices
        b = b.strip() # getting rid of \n from the end
        
        # we first search if the value inside variable a exists in the dictionary or not
        if(a in graph):
            # if yes, then append() the value in b to a
            graph[a].append(b)
        else:
            # create a new list in graph with a as the key and b as the value
            graph[a] = [b]
        # print("a",a)
        # print("b",b)
        counter+=1    
    
    print(graph)
    printGraph(graph, None)

    
# TO DO
# This method must be completed by you
# You should code in such a way that the output should be
 # 1 -> 2,4
 # 2 -> 4
 # 3 -> 1,4
 # 4 -> 2
# notice this method takes both the graphs as parameters
# this means you have print the same output in the same style for both the datastructures
# if graph is none then print from listGraph
# if listGraph is none then print from graph
def printGraph(graph,listGraph):  
    # Your code
    if (listGraph == None):
        print()

        for key, val in graph.items():
            print(f"{key}->" + ",".join(val))
        print()
        print()
        print()

    if (graph == None):
        print()    

        for i in range(0, len(listGraph), 2):
            if listGraph[i] == 0:
                break
            else:
                print(f"{listGraph[i]}->" + ",".join(listGraph[i+1]))

    # return # delete this line

# TO DO
# I have shown you how to build a graph using a dictionary of list
# now your job is to build a graph using list of lists [[E,B],[C,D]]
# it means A -> E,B and B -> C,D
def buildGraphUsingListofLists(c,f):
    
    listGraph = []   # do not change the name of the variable
    f.seek(0)
    lines = f.readline().strip()
    listGraph = [0]*(int(lines)*2)
    c = f.readline().strip()
    initial = 0

    for i in range(6):
        readline = f.readline()
        a,b = readline.split(",")
        # b = readline.split(",")
        b = b.strip()

        if a in listGraph:
            add = listGraph.index(a)+1
            listGraph[add].append(b)
        
        else:
            listGraph[initial] = a
            listGraph[initial+1] = [b]
            initial = initial + 2
    print(listGraph)

    printGraph(None,listGraph)
    # return # delete this line
# ======================Program starts here.========================

# read file using the readFile() method
readFile()