# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10WZvQKdYnXtsPtbcmEzV5MvZ__Yp3GH2
"""

##  TASK 3 er 2

with open("input3.txt",'r') as file_in:
    with open("output3.txt", "w") as file_out:
        lines = (file_in.readline())
        num = lines.split()
        arr = []


        def partition(arr,low,high):
            pivot = arr[high]
            i = low-1
            for j in range(low,high):
                if arr[j] < pivot:
                    i = i+1
                    (arr[i],arr[j]) = (arr[j],arr[i])
            (arr[i+1],arr[high]) = (arr[high],arr[i+1])
            return (i+1)

        def quicksort(arr,low,high):
            if low<high:
                pi = partition(arr,low,high)
                quicksort(arr,low,pi-1)
                quicksort(arr,pi+1,high)
            
        for i in num:
            arr.append(int(i))
        quicksort(arr,0,len(arr)-1)
        # sArr = quicksort(arr,0,len(arr)-1)
        
        for i in arr:
            file_out.write(str(i) + " ")
        # file_out.write(str(sArr))
        file_out.write("\n\n")

        def findk(arrr, low, high, k):
            pi = partition(arrr, low, high)

            if (pi == k):
                file_out.write(str(arrr[pi]) + "\n")
            elif (k > pi):
                findk(arrr,pi+1,high,k)
            elif (k < pi):
                findk(arrr,low,pi-1,k)

        arr = [1, 3, 4, 5, 9, 10, 10]
        
        find1 = findk(arr, 0, len(arr) - 1, 4)
        find2 = findk(arr, 0, len(arr) - 1, 6)
        find3 = findk(arr, 0, len(arr) - 1, 1)
        # print("\n")