# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10WZvQKdYnXtsPtbcmEzV5MvZ__Yp3GH2
"""

# TASK 1

with open("input1.txt", "r") as filein:
    with open("output1.txt", "w") as fileout:

        line = int(filein.readline())
        marks = filein.readline().split()
        id_no = filein.readline().split()
        for i in range(len(id_no)):
            id_no[i] = int(id_no[i])
        for i in range(len(marks)):
            marks[i] = int(marks[i])

        for i in range(line-1):
            temp = id_no[i+1]
            temp2 = marks[i+1]
            j = i

            while j >= 0:
                if id_no[j] < temp:
                    id_no[j+1] = id_no[j]
                    marks[j+1] = marks[j]
                else:
                    break
                j = j - 1
            id_no[j+1] = temp
            marks[j+1] = temp2
        for i in marks:
            fileout.write(str(i)  +  " ")