# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10WZvQKdYnXtsPtbcmEzV5MvZ__Yp3GH2
"""

# task 2

with open('input2.txt','r') as filein:
    with open('output2.txt','w') as fileout:

        line = int(filein.readline())
        arr=filein.readline().split()

        for i in range(len(arr)):
            arr[i] = int(arr[i])

        import math

        def merge(arr, p, m, q):
            n1 = m - p + 1
            n2 = q - m
            L = [0] * (n1+1)
            R = [0] * (n2+1)
            for i in range(n1):
                L[i] = arr[p + i]
        
            for j in range(n2):
                R[j] = arr[m + 1 + j]

            L[n1] = math.inf
            R[n2]=math.inf
            i = 0     
            j = 0     
            k = p     

            # for k in range(p, q):
            #     if L[i] <= R[j]:
            #         arr[k] = L[i]
            #         i += 1
            #     else:
            #         arr[k] = R[j]
            #         j += 1            
            
            while True:
                if L[i] <= R[j]:
                    arr[k] = L[i]
                    i += 1
                else:
                    arr[k] = R[j]
                    j += 1
                if L[i]==math.inf and R[j]==math.inf:
                    break
                k+=1
            
        
        def mergesort(arr, p, q):
            if p < q:
                m = p+(q-p)//2
                mergesort(arr, p, m)
                mergesort(arr, m+1, q)
                merge(arr, p, m, q)
                
        mergesort(arr, 0, len(arr)-1)
                
        
        for i in range(len(arr)):
            fileout.write(str(arr[i]) + " ")