# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10WZvQKdYnXtsPtbcmEzV5MvZ__Yp3GH2
"""

with open("input4.txt", "r") as file_in:
    with open("output4.txt", "w") as file_out:
        
        nameLIST = []
        patientserial=[]



        
        def seeDoctor():
            printQueue()
            patientserial.pop(0)
            nameLIST.pop(0)

        def enqueue(paitent):
            nameLIST.append(paitent[0])
            patientserial.append(paitent[1])

        def bubble_sort(patientserial):
            for i in range(len(patientserial)):
                for j in range(len(patientserial)-1):
                    if patientserial[j] > patientserial[j+1]:
                        (patientserial[j],patientserial[j+1]) = (patientserial[j+1],patientserial[j])
                        (nameLIST[j],nameLIST[j+1]) = (nameLIST[j+1],nameLIST[j])

        
        def heapSort(patientserial):
            n = len(patientserial)
                
            for i in range(n - 1, 0, -1):
                (patientserial[i], patientserial[0]) = (patientserial[0], patientserial[i])  
                (nameLIST[i], nameLIST[0]) = (nameLIST[0], nameLIST[i]) 

        def printQueue():
            file_out.write(f"{nameLIST[0]}\n")


        def do_heap_sort(filein,file_out):
            filein.seek(0)
            file_out.write("\n")

            for i in range(13):
                paitent=filein.readline().strip()
                if paitent == "see doctor":
                    seeDoctor()

                else:
                    enqueue(paitent.split())
                    heapSort(patientserial)